version: '2.2'
networks:
    app-net:
        driver: bridge
services:
    urllookup:
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./app:/app/
        networks:
            - app-net
    redis:
        build:
            context: ./redis
            dockerfile: Dockerfile
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
        volumes:
            - ./redis/data:/bitnami/redis/data/
        ports:
            - "6379:6379"
        networks:
            - app-net
